BEGIN;

ALTER TABLE trade_stock_order
ADD COLUMN IF NOT EXISTS "manual" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE trade_future_order
ADD COLUMN IF NOT EXISTS "manual" BOOLEAN NOT NULL DEFAULT FALSE;

COMMIT;
