// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: trade.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradeInterfaceClient is the client API for TradeInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeInterfaceClient interface {
	// BuyStock is the interface for buying stock
	BuyStock(ctx context.Context, in *StockOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// SellStock is the interface for selling stock
	SellStock(ctx context.Context, in *StockOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// SellFirstStock is the interface for selling first stock
	SellFirstStock(ctx context.Context, in *StockOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// CancelStock is the interface for canceling stock
	CancelStock(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*TradeResult, error)
	// BuyFuture is the interface for buying future
	BuyFuture(ctx context.Context, in *FutureOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// SellFuture is the interface for selling future
	SellFuture(ctx context.Context, in *FutureOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// SellFirstFuture is the interface for selling first future
	SellFirstFuture(ctx context.Context, in *FutureOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// CancelFuture is the interface for canceling future
	CancelFuture(ctx context.Context, in *FutureOrderID, opts ...grpc.CallOption) (*TradeResult, error)
	// BuyFuture is the interface for buying future
	BuyOption(ctx context.Context, in *OptionOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// SellFuture is the interface for selling future
	SellOption(ctx context.Context, in *OptionOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// SellFirstFuture is the interface for selling first future
	SellFirstOption(ctx context.Context, in *OptionOrderDetail, opts ...grpc.CallOption) (*TradeResult, error)
	// CancelFuture is the interface for canceling future
	CancelOption(ctx context.Context, in *OptionOrderID, opts ...grpc.CallOption) (*TradeResult, error)
	// GetLocalOrderStatusArr is the interface for getting local order status array
	GetLocalOrderStatusArr(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSimulateOrderStatusArr is the interface for getting simulate order status array
	GetSimulateOrderStatusArr(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetOrderStatusByID is the interface for getting order status by id
	GetOrderStatusByID(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*TradeResult, error)
	// GetNonBlockOrderStatusArr is the interface for getting non block order status array
	GetNonBlockOrderStatusArr(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ErrorMessage, error)
	// GetFuturePosition is the interface for getting future position
	GetFuturePosition(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FuturePositionArr, error)
}

type tradeInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeInterfaceClient(cc grpc.ClientConnInterface) TradeInterfaceClient {
	return &tradeInterfaceClient{cc}
}

func (c *tradeInterfaceClient) BuyStock(ctx context.Context, in *StockOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/BuyStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) SellStock(ctx context.Context, in *StockOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/SellStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) SellFirstStock(ctx context.Context, in *StockOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/SellFirstStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) CancelStock(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/CancelStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) BuyFuture(ctx context.Context, in *FutureOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/BuyFuture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) SellFuture(ctx context.Context, in *FutureOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/SellFuture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) SellFirstFuture(ctx context.Context, in *FutureOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/SellFirstFuture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) CancelFuture(ctx context.Context, in *FutureOrderID, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/CancelFuture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) BuyOption(ctx context.Context, in *OptionOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/BuyOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) SellOption(ctx context.Context, in *OptionOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/SellOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) SellFirstOption(ctx context.Context, in *OptionOrderDetail, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/SellFirstOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) CancelOption(ctx context.Context, in *OptionOrderID, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/CancelOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) GetLocalOrderStatusArr(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/GetLocalOrderStatusArr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) GetSimulateOrderStatusArr(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/GetSimulateOrderStatusArr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) GetOrderStatusByID(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*TradeResult, error) {
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/GetOrderStatusByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) GetNonBlockOrderStatusArr(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ErrorMessage, error) {
	out := new(ErrorMessage)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/GetNonBlockOrderStatusArr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeInterfaceClient) GetFuturePosition(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FuturePositionArr, error) {
	out := new(FuturePositionArr)
	err := c.cc.Invoke(ctx, "/toc_python_forwarder.TradeInterface/GetFuturePosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeInterfaceServer is the server API for TradeInterface service.
// All implementations must embed UnimplementedTradeInterfaceServer
// for forward compatibility
type TradeInterfaceServer interface {
	// BuyStock is the interface for buying stock
	BuyStock(context.Context, *StockOrderDetail) (*TradeResult, error)
	// SellStock is the interface for selling stock
	SellStock(context.Context, *StockOrderDetail) (*TradeResult, error)
	// SellFirstStock is the interface for selling first stock
	SellFirstStock(context.Context, *StockOrderDetail) (*TradeResult, error)
	// CancelStock is the interface for canceling stock
	CancelStock(context.Context, *OrderID) (*TradeResult, error)
	// BuyFuture is the interface for buying future
	BuyFuture(context.Context, *FutureOrderDetail) (*TradeResult, error)
	// SellFuture is the interface for selling future
	SellFuture(context.Context, *FutureOrderDetail) (*TradeResult, error)
	// SellFirstFuture is the interface for selling first future
	SellFirstFuture(context.Context, *FutureOrderDetail) (*TradeResult, error)
	// CancelFuture is the interface for canceling future
	CancelFuture(context.Context, *FutureOrderID) (*TradeResult, error)
	// BuyFuture is the interface for buying future
	BuyOption(context.Context, *OptionOrderDetail) (*TradeResult, error)
	// SellFuture is the interface for selling future
	SellOption(context.Context, *OptionOrderDetail) (*TradeResult, error)
	// SellFirstFuture is the interface for selling first future
	SellFirstOption(context.Context, *OptionOrderDetail) (*TradeResult, error)
	// CancelFuture is the interface for canceling future
	CancelOption(context.Context, *OptionOrderID) (*TradeResult, error)
	// GetLocalOrderStatusArr is the interface for getting local order status array
	GetLocalOrderStatusArr(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// GetSimulateOrderStatusArr is the interface for getting simulate order status array
	GetSimulateOrderStatusArr(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// GetOrderStatusByID is the interface for getting order status by id
	GetOrderStatusByID(context.Context, *OrderID) (*TradeResult, error)
	// GetNonBlockOrderStatusArr is the interface for getting non block order status array
	GetNonBlockOrderStatusArr(context.Context, *emptypb.Empty) (*ErrorMessage, error)
	// GetFuturePosition is the interface for getting future position
	GetFuturePosition(context.Context, *emptypb.Empty) (*FuturePositionArr, error)
	mustEmbedUnimplementedTradeInterfaceServer()
}

// UnimplementedTradeInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedTradeInterfaceServer struct {
}

func (UnimplementedTradeInterfaceServer) BuyStock(context.Context, *StockOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyStock not implemented")
}
func (UnimplementedTradeInterfaceServer) SellStock(context.Context, *StockOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellStock not implemented")
}
func (UnimplementedTradeInterfaceServer) SellFirstStock(context.Context, *StockOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellFirstStock not implemented")
}
func (UnimplementedTradeInterfaceServer) CancelStock(context.Context, *OrderID) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelStock not implemented")
}
func (UnimplementedTradeInterfaceServer) BuyFuture(context.Context, *FutureOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyFuture not implemented")
}
func (UnimplementedTradeInterfaceServer) SellFuture(context.Context, *FutureOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellFuture not implemented")
}
func (UnimplementedTradeInterfaceServer) SellFirstFuture(context.Context, *FutureOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellFirstFuture not implemented")
}
func (UnimplementedTradeInterfaceServer) CancelFuture(context.Context, *FutureOrderID) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelFuture not implemented")
}
func (UnimplementedTradeInterfaceServer) BuyOption(context.Context, *OptionOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyOption not implemented")
}
func (UnimplementedTradeInterfaceServer) SellOption(context.Context, *OptionOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellOption not implemented")
}
func (UnimplementedTradeInterfaceServer) SellFirstOption(context.Context, *OptionOrderDetail) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellFirstOption not implemented")
}
func (UnimplementedTradeInterfaceServer) CancelOption(context.Context, *OptionOrderID) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOption not implemented")
}
func (UnimplementedTradeInterfaceServer) GetLocalOrderStatusArr(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalOrderStatusArr not implemented")
}
func (UnimplementedTradeInterfaceServer) GetSimulateOrderStatusArr(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimulateOrderStatusArr not implemented")
}
func (UnimplementedTradeInterfaceServer) GetOrderStatusByID(context.Context, *OrderID) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderStatusByID not implemented")
}
func (UnimplementedTradeInterfaceServer) GetNonBlockOrderStatusArr(context.Context, *emptypb.Empty) (*ErrorMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonBlockOrderStatusArr not implemented")
}
func (UnimplementedTradeInterfaceServer) GetFuturePosition(context.Context, *emptypb.Empty) (*FuturePositionArr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFuturePosition not implemented")
}
func (UnimplementedTradeInterfaceServer) mustEmbedUnimplementedTradeInterfaceServer() {}

// UnsafeTradeInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeInterfaceServer will
// result in compilation errors.
type UnsafeTradeInterfaceServer interface {
	mustEmbedUnimplementedTradeInterfaceServer()
}

func RegisterTradeInterfaceServer(s grpc.ServiceRegistrar, srv TradeInterfaceServer) {
	s.RegisterService(&TradeInterface_ServiceDesc, srv)
}

func _TradeInterface_BuyStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).BuyStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/BuyStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).BuyStock(ctx, req.(*StockOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_SellStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).SellStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/SellStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).SellStock(ctx, req.(*StockOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_SellFirstStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).SellFirstStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/SellFirstStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).SellFirstStock(ctx, req.(*StockOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_CancelStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).CancelStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/CancelStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).CancelStock(ctx, req.(*OrderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_BuyFuture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FutureOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).BuyFuture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/BuyFuture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).BuyFuture(ctx, req.(*FutureOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_SellFuture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FutureOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).SellFuture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/SellFuture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).SellFuture(ctx, req.(*FutureOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_SellFirstFuture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FutureOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).SellFirstFuture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/SellFirstFuture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).SellFirstFuture(ctx, req.(*FutureOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_CancelFuture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FutureOrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).CancelFuture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/CancelFuture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).CancelFuture(ctx, req.(*FutureOrderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_BuyOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).BuyOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/BuyOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).BuyOption(ctx, req.(*OptionOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_SellOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).SellOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/SellOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).SellOption(ctx, req.(*OptionOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_SellFirstOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionOrderDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).SellFirstOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/SellFirstOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).SellFirstOption(ctx, req.(*OptionOrderDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_CancelOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionOrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).CancelOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/CancelOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).CancelOption(ctx, req.(*OptionOrderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_GetLocalOrderStatusArr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).GetLocalOrderStatusArr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/GetLocalOrderStatusArr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).GetLocalOrderStatusArr(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_GetSimulateOrderStatusArr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).GetSimulateOrderStatusArr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/GetSimulateOrderStatusArr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).GetSimulateOrderStatusArr(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_GetOrderStatusByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).GetOrderStatusByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/GetOrderStatusByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).GetOrderStatusByID(ctx, req.(*OrderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_GetNonBlockOrderStatusArr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).GetNonBlockOrderStatusArr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/GetNonBlockOrderStatusArr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).GetNonBlockOrderStatusArr(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeInterface_GetFuturePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeInterfaceServer).GetFuturePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/toc_python_forwarder.TradeInterface/GetFuturePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeInterfaceServer).GetFuturePosition(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeInterface_ServiceDesc is the grpc.ServiceDesc for TradeInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "toc_python_forwarder.TradeInterface",
	HandlerType: (*TradeInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyStock",
			Handler:    _TradeInterface_BuyStock_Handler,
		},
		{
			MethodName: "SellStock",
			Handler:    _TradeInterface_SellStock_Handler,
		},
		{
			MethodName: "SellFirstStock",
			Handler:    _TradeInterface_SellFirstStock_Handler,
		},
		{
			MethodName: "CancelStock",
			Handler:    _TradeInterface_CancelStock_Handler,
		},
		{
			MethodName: "BuyFuture",
			Handler:    _TradeInterface_BuyFuture_Handler,
		},
		{
			MethodName: "SellFuture",
			Handler:    _TradeInterface_SellFuture_Handler,
		},
		{
			MethodName: "SellFirstFuture",
			Handler:    _TradeInterface_SellFirstFuture_Handler,
		},
		{
			MethodName: "CancelFuture",
			Handler:    _TradeInterface_CancelFuture_Handler,
		},
		{
			MethodName: "BuyOption",
			Handler:    _TradeInterface_BuyOption_Handler,
		},
		{
			MethodName: "SellOption",
			Handler:    _TradeInterface_SellOption_Handler,
		},
		{
			MethodName: "SellFirstOption",
			Handler:    _TradeInterface_SellFirstOption_Handler,
		},
		{
			MethodName: "CancelOption",
			Handler:    _TradeInterface_CancelOption_Handler,
		},
		{
			MethodName: "GetLocalOrderStatusArr",
			Handler:    _TradeInterface_GetLocalOrderStatusArr_Handler,
		},
		{
			MethodName: "GetSimulateOrderStatusArr",
			Handler:    _TradeInterface_GetSimulateOrderStatusArr_Handler,
		},
		{
			MethodName: "GetOrderStatusByID",
			Handler:    _TradeInterface_GetOrderStatusByID_Handler,
		},
		{
			MethodName: "GetNonBlockOrderStatusArr",
			Handler:    _TradeInterface_GetNonBlockOrderStatusArr_Handler,
		},
		{
			MethodName: "GetFuturePosition",
			Handler:    _TradeInterface_GetFuturePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade.proto",
}
