// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/analyze/reborn": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyze V1"
                ],
                "summary": "Get reborn targets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.reborn"
                            }
                        }
                    }
                }
            }
        },
        "/v1/basic/config": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic V1"
                ],
                "summary": "Get all config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Config"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/basic/stock": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic V1"
                ],
                "summary": "Get all repo stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "num",
                        "name": "num",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.stockDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/basic/usage/shioaji": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic V1"
                ],
                "summary": "Get shioaji usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.ShioajiUsage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/fcm/announcement": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FCM V1"
                ],
                "summary": "Announce message to all devices",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.announceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/fcm/push": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FCM V1"
                ],
                "summary": "Push message to devices which has push token",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.pushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/history/day-kbar/{stock}/{start_date}/{interval}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History V1"
                ],
                "summary": "Get kbar data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "stock",
                        "name": "stock",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "start_date",
                        "name": "start_date",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "interval",
                        "name": "interval",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.StockHistoryKbar"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/logout": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/order": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Manual insert future order",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.manualInsertFutureOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/account/balance": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account V1"
                ],
                "summary": "Get account balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.accountSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/all": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Get all order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.allOrder"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/balance": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Get all trade balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.tradeBalance"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/balance/future/last": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Get last future trade balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.FutureTradeBalance"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/balance/stock/last": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Get last stock trade balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.StockTradeBalance"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/date/{tradeday}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Get all order by trade day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tradeday",
                        "name": "tradeday",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.futureOrders"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Update trade balance by trade day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tradeday",
                        "name": "tradeday",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.futureOrders"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/future/{order-id}": {
            "patch": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Move future order to latest trade day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order-id",
                        "name": "order-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/order/stock/{order-id}": {
            "patch": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order V1"
                ],
                "summary": "Move stock order to latest trade day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order-id",
                        "name": "order-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/refresh": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.UnauthorizedResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/stream/index": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream V1"
                ],
                "summary": "Get index",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.TradeIndex"
                        }
                    }
                }
            }
        },
        "/v1/stream/tse/snapshot": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream V1"
                ],
                "summary": "Get TSE snapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.StockSnapShot"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/targets": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Targets V1"
                ],
                "summary": "Get targets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.StockTarget"
                            }
                        }
                    }
                }
            }
        },
        "/v1/trade/stock/buy/lot": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade V1"
                ],
                "summary": "Buy lot stock",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.lotStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.tradeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.UnauthorizedResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/trade/stock/buy/odd": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade V1"
                ],
                "summary": "Buy odd stock",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.oddStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.tradeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.UnauthorizedResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "New user",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/auth": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Update auth trade user",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.UnauthorizedResponseBody"
                        }
                    }
                }
            }
        },
        "/v1/user/push-token": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Update user push token",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.userPushTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.UnauthorizedResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resp.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/verify/{user}/{code}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User V1"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginBody": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponseBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "expire": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.LogoutResponseBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "auth.RefreshResponseBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "expire": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.UnauthorizedResponseBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "config.AnalyzeStock": {
            "type": "object",
            "properties": {
                "AllInOutRatio": {
                    "type": "number"
                },
                "AllOutInRatio": {
                    "type": "number"
                },
                "CloseChangeRatioHigh": {
                    "type": "number"
                },
                "CloseChangeRatioLow": {
                    "type": "number"
                },
                "MAPeriod": {
                    "type": "integer"
                },
                "MaxHoldTime": {
                    "type": "number"
                },
                "RSIMinCount": {
                    "type": "integer"
                },
                "TickAnalyzePeriod": {
                    "type": "number"
                },
                "VolumePRLimit": {
                    "type": "number"
                }
            }
        },
        "config.Config": {
            "type": "object",
            "properties": {
                "AnalyzeStock": {
                    "$ref": "#/definitions/config.AnalyzeStock"
                },
                "History": {
                    "$ref": "#/definitions/config.History"
                },
                "ManualTrade": {
                    "type": "boolean"
                },
                "Quota": {
                    "$ref": "#/definitions/config.Quota"
                },
                "Simulation": {
                    "type": "boolean"
                },
                "TargetStock": {
                    "$ref": "#/definitions/config.TargetStock"
                },
                "TradeFuture": {
                    "$ref": "#/definitions/config.TradeFuture"
                },
                "TradeStock": {
                    "$ref": "#/definitions/config.TradeStock"
                }
            }
        },
        "config.History": {
            "type": "object",
            "properties": {
                "HistoryClosePeriod": {
                    "type": "integer"
                },
                "HistoryKbarPeriod": {
                    "type": "integer"
                },
                "HistoryTickPeriod": {
                    "type": "integer"
                }
            }
        },
        "config.PriceLimit": {
            "type": "object",
            "properties": {
                "High": {
                    "type": "number"
                },
                "Low": {
                    "type": "number"
                }
            }
        },
        "config.Quota": {
            "type": "object",
            "properties": {
                "FutureTradeFee": {
                    "type": "integer"
                },
                "StockFeeDiscount": {
                    "type": "number"
                },
                "StockTradeQuota": {
                    "type": "integer"
                }
            }
        },
        "config.TargetStock": {
            "type": "object",
            "properties": {
                "BlackCategory": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "BlackStock": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "LimitVolume": {
                    "type": "integer"
                },
                "PriceLimit": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.PriceLimit"
                    }
                },
                "RealTimeRank": {
                    "type": "integer"
                }
            }
        },
        "config.TradeFuture": {
            "type": "object",
            "properties": {
                "AllowTrade": {
                    "type": "boolean"
                },
                "BuySellWaitTime": {
                    "type": "integer"
                },
                "InOutRatio": {
                    "type": "number"
                },
                "MaxHoldTime": {
                    "type": "integer"
                },
                "OutInRatio": {
                    "type": "number"
                },
                "Quantity": {
                    "type": "integer"
                },
                "RateChangeRatio": {
                    "type": "number"
                },
                "RateLimit": {
                    "type": "number"
                },
                "Subscribe": {
                    "type": "boolean"
                },
                "TargetBalanceHigh": {
                    "type": "number"
                },
                "TargetBalanceLow": {
                    "type": "number"
                },
                "TickInterval": {
                    "type": "integer"
                },
                "TradeOutWaitTimes": {
                    "type": "integer"
                },
                "TradeTimeRange": {
                    "$ref": "#/definitions/config.TradeTimeRange"
                }
            }
        },
        "config.TradeStock": {
            "type": "object",
            "properties": {
                "AllowTrade": {
                    "type": "boolean"
                },
                "CancelWaitTime": {
                    "type": "integer"
                },
                "HoldTimeFromOpen": {
                    "type": "number"
                },
                "Odd": {
                    "type": "boolean"
                },
                "Subscribe": {
                    "type": "boolean"
                },
                "TotalOpenTime": {
                    "type": "number"
                },
                "TradeInEndTime": {
                    "type": "number"
                },
                "TradeInWaitTime": {
                    "type": "integer"
                },
                "TradeOutWaitTime": {
                    "type": "integer"
                }
            }
        },
        "config.TradeTimeRange": {
            "type": "object",
            "properties": {
                "FirstPartDuration": {
                    "type": "integer"
                },
                "SecondPartDuration": {
                    "type": "integer"
                }
            }
        },
        "entity.AccountBalance": {
            "type": "object",
            "properties": {
                "available_margin": {
                    "type": "number"
                },
                "balance": {
                    "type": "number"
                },
                "bank_id": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "risk_indicator": {
                    "type": "number"
                },
                "today_margin": {
                    "type": "number"
                },
                "yesterday_margin": {
                    "type": "number"
                }
            }
        },
        "entity.Future": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "delivery_date": {
                    "type": "string"
                },
                "delivery_month": {
                    "type": "string"
                },
                "limit_down": {
                    "type": "number"
                },
                "limit_up": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "reference": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "underlying_kind": {
                    "type": "string"
                },
                "unit": {
                    "type": "integer"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "entity.FutureOrder": {
            "type": "object",
            "properties": {
                "base_order": {
                    "$ref": "#/definitions/entity.OrderDetail"
                },
                "code": {
                    "type": "string"
                },
                "future": {
                    "$ref": "#/definitions/entity.Future"
                },
                "position": {
                    "type": "integer"
                }
            }
        },
        "entity.FutureTradeBalance": {
            "type": "object",
            "properties": {
                "forward": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "reverse": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "trade_count": {
                    "type": "integer"
                },
                "trade_day": {
                    "type": "string"
                }
            }
        },
        "entity.IndexStatus": {
            "type": "object",
            "properties": {
                "break_count": {
                    "type": "integer"
                },
                "price_chg": {
                    "type": "number"
                }
            }
        },
        "entity.OrderAction": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "ActionNone",
                "ActionBuy",
                "ActionSell"
            ]
        },
        "entity.OrderDetail": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/entity.OrderAction"
                },
                "order_id": {
                    "type": "string"
                },
                "order_time": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/entity.OrderStatus"
                }
            }
        },
        "entity.OrderStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7
            ],
            "x-enum-varnames": [
                "StatusUnknow",
                "StatusPendingSubmit",
                "StatusPreSubmitted",
                "StatusSubmitted",
                "StatusFailed",
                "StatusCancelled",
                "StatusFilled",
                "StatusPartFilled"
            ]
        },
        "entity.ShioajiUsage": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "integer"
                },
                "traffic_usage": {
                    "type": "number"
                },
                "traffic_usage_percents": {
                    "type": "number"
                }
            }
        },
        "entity.Stock": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "day_trade": {
                    "type": "boolean"
                },
                "delivery_date": {
                    "type": "string"
                },
                "delivery_month": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "last_close": {
                    "type": "number"
                },
                "limit_down": {
                    "type": "number"
                },
                "limit_up": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "reference": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "underlying_kind": {
                    "type": "string"
                },
                "unit": {
                    "type": "integer"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "entity.StockHistoryKbar": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "kbar_time": {
                    "type": "string"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "stock": {
                    "$ref": "#/definitions/entity.Stock"
                },
                "stock_num": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "entity.StockOrder": {
            "type": "object",
            "properties": {
                "base_order": {
                    "$ref": "#/definitions/entity.OrderDetail"
                },
                "lot": {
                    "type": "integer"
                },
                "share": {
                    "type": "integer"
                },
                "stock": {
                    "$ref": "#/definitions/entity.Stock"
                },
                "stock_num": {
                    "type": "string"
                }
            }
        },
        "entity.StockSnapShot": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "amount_sum": {
                    "type": "integer"
                },
                "chg_type": {
                    "type": "string"
                },
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "pct_chg": {
                    "type": "number"
                },
                "price_chg": {
                    "type": "number"
                },
                "snap_time": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "stock_num": {
                    "type": "string"
                },
                "tick_type": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                },
                "volume_ratio": {
                    "type": "number"
                },
                "volume_sum": {
                    "type": "integer"
                },
                "yesterday_volume": {
                    "type": "number"
                }
            }
        },
        "entity.StockTarget": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "stock": {
                    "$ref": "#/definitions/entity.Stock"
                },
                "stock_num": {
                    "type": "string"
                },
                "trade_day": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "entity.StockTradeBalance": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "integer"
                },
                "forward": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "original_balance": {
                    "type": "integer"
                },
                "reverse": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "trade_count": {
                    "type": "integer"
                },
                "trade_day": {
                    "type": "string"
                }
            }
        },
        "entity.TradeIndex": {
            "type": "object",
            "properties": {
                "nasdaq": {
                    "$ref": "#/definitions/entity.IndexStatus"
                },
                "nf": {
                    "$ref": "#/definitions/entity.IndexStatus"
                },
                "otc": {
                    "$ref": "#/definitions/entity.IndexStatus"
                },
                "tse": {
                    "$ref": "#/definitions/entity.IndexStatus"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "resp.Response": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "v1.accountSummary": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.AccountBalance"
                    }
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "v1.allOrder": {
            "type": "object",
            "properties": {
                "future": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FutureOrder"
                    }
                },
                "stock": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.StockOrder"
                    }
                }
            }
        },
        "v1.announceRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.futureOrders": {
            "type": "object",
            "properties": {
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FutureOrder"
                    }
                }
            }
        },
        "v1.lotStockRequest": {
            "type": "object",
            "properties": {
                "lot": {
                    "type": "integer"
                },
                "num": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "v1.manualInsertFutureOrderRequest": {
            "type": "object",
            "required": [
                "action",
                "code",
                "order_time",
                "price",
                "quantity"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/entity.OrderAction"
                },
                "code": {
                    "type": "string"
                },
                "order_time": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "v1.oddStockRequest": {
            "type": "object",
            "properties": {
                "num": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "share": {
                    "type": "integer"
                }
            }
        },
        "v1.pushRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "v1.reborn": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "stocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Stock"
                    }
                }
            }
        },
        "v1.stockDetailResponse": {
            "type": "object",
            "properties": {
                "stock_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Stock"
                    }
                }
            }
        },
        "v1.tradeBalance": {
            "type": "object",
            "properties": {
                "future": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FutureTradeBalance"
                    }
                },
                "stock": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.StockTradeBalance"
                    }
                }
            }
        },
        "v1.tradeResponse": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.userPushTokenRequest": {
            "type": "object",
            "properties": {
                "push_token": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.5.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "TMT OpenAPI",
	Description:      "Toc Machine Trading's API docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
